name: release

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Update tzdata
          run: sudo apt-get update && sudo apt-get install -y tzdata

        - name: Restore
          run: dotnet restore --nologo

        - name: Build
          run: dotnet build -c Release --nologo --no-restore

        - name: Test
          run: dotnet test -c Release --nologo --no-build -l GitHubActions -l "trx;LogFilePrefix=testresults_${{ runner.os }}"

        - name: Pack
          run: dotnet pack -c Release --nologo --no-build

        - name: Push TimeZoneConverter to NuGet
          run: dotnet nuget push --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} src/TimeZoneConverter/**/*.nupkg

        - name: Push TimeZoneConverter.Posix to NuGet
          run: dotnet nuget push --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} src/TimeZoneConverter.Posix/**/*.nupkg

        - name: Archive Artifacts
          uses: actions/upload-artifact@v5
          with:
            name: nuget-packages
            path: src/**/Release/*.*nupkg
            if-no-files-found: error
