name: release

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Update tzdata
          run: sudo apt-get update && sudo apt-get install -y tzdata

        - name: Set dotnet install dir on Windows
          if: runner.os == 'Windows'
          run: echo "DOTNET_INSTALL_DIR=D:\dotnet" >> $GITHUB_ENV

        - name: Install .NET SDKs
          uses: actions/setup-dotnet@v5
          with:
            dotnet-version: |
              3.1.x
              6.0.x
              8.0.x
              9.0.x

        - name: Restore
          run: dotnet restore --nologo

        - name: Build
          run: dotnet build -c Release --nologo --no-restore

        - name: Test
          run: dotnet test -c Release --nologo --no-build -l GitHubActions -l "trx;LogFilePrefix=testresults_${{ runner.os }}"

        - name: Pack
          run: dotnet pack -c Release --nologo --no-build

        - name: Push to NuGet
          run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} **/*.nupkg

        - name: Archive Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: nuget-packages
            path: src/**/Release/*.*nupkg
            if-no-files-found: error
